---
# Installed Ansible version on the node:
# ansible [core 2.16.3]

- name: Block port 8080 with UFW (Firewall Demo)
  hosts: all
  become: yes

  tasks:
    - name: Reset UFW to a clean state
      ansible.builtin.command: ufw --force reset

    - name: Allow SSH on port 22
      ansible.builtin.command: ufw allow 22/tcp

    - name: Deny HTTP on port 8080
      ansible.builtin.command: ufw deny 8080/tcp

    - name: Enable UFW
      ansible.builtin.command: ufw --force enable

    - name: Show UFW status
      ansible.builtin.command: ufw status numbered
      register: ufw_status

    - name: Print UFW status
      ansible.builtin.debug:
        var: ufw_status.stdout_lines





