# Installed Ansible version on the node:
# ansible [core 2.16.3]

---
- name: Configure firewall on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Ensure UFW is enabled with default deny incoming
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Ensure SSH is allowed
      community.general.ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Remove any existing ALLOW rule for port 8080
      community.general.ufw:
        rule: allow
        port: 8080
        proto: tcp
        delete: true

    - name: Deny incoming traffic on port 8080
      community.general.ufw:
        rule: deny
        port: 8080
        proto: tcp


