---
# Installed Ansible version on the node:
# ansible [core 2.16.3]

- name: Configure firewall on Ubuntu
  hosts: demo
  become: yes

  vars:
    ansible_user: ubuntu
    ansible_host: 54.67.6.45
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_rsa
    ansible_connection: ssh

  tasks:
    - name: Reset UFW rules to clean state
      ansible.builtin.command: ufw --force reset

    - name: Allow SSH on port 22
      ansible.builtin.command: ufw allow 22/tcp

    - name: Deny HTTP traffic on port 8080
      ansible.builtin.command: ufw deny 8080/tcp

    - name: Enable firewall
      ansible.builtin.command: ufw --force enable

