---
# Installed Ansible version on the node:
# ansible [core 2.16.3]

---
- name: Block port 8080 on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Deny port 8080
      ansible.builtin.command: ufw deny 8080/tcp

    - name: Enable UFW
      ansible.builtin.command: ufw --force enable


