# Installed Ansible version on the node:
# ansible [core 2.16.3]

---
- name: Configure firewall on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Reset UFW rules to a clean state
      ansible.builtin.command: ufw --force reset

    - name: Allow SSH on port 22
      ansible.builtin.command: ufw allow 22/tcp

    - name: Deny HTTP traffic on port 8080
      ansible.builtin.command: ufw deny 8080/tcp

    - name: Enable UFW with new rules
      ansible.builtin.command: ufw --force enable
