# ============================
# INVENTORY SECTION
# ============================
all:
  hosts:
    ubuntu_vm:
      ansible_host: 13.57.10.68
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

---
# ============================
# PLAYBOOK SECTION
# ============================
- name: Block port 8080 on Ubuntu VM
  hosts: all
  become: yes

  tasks:
    - name: Ensure UFW is installed
      ansible.builtin.apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Block port 8080
      community.general.ufw:
        rule: deny
        port: 8080
        proto: tcp
