---
- name: Install curl on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present
